# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(110, 510, 101, 31))
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 520, 47, 13))
        self.label.setObjectName("label")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(50, 20, 691, 451))
        self.widget.setObjectName("widget")
        self.ratingWidget = QtWidgets.QTableWidget(self.widget)
        self.ratingWidget.setGeometry(QtCore.QRect(20, 30, 631, 192))
        self.ratingWidget.setObjectName("ratingWidget")
        self.ratingWidget.setColumnCount(0)
        self.ratingWidget.setRowCount(0)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuRating = QtWidgets.QMenu(self.menubar)
        self.menuRating.setObjectName("menuRating")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuUser = QtWidgets.QMenu(self.menubar)
        self.menuUser.setObjectName("menuUser")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setEnabled(True)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.viewMyRatingsAction = QtWidgets.QAction(MainWindow)
        self.viewMyRatingsAction.setObjectName("viewMyRatingsAction")
        self.viewAllRatingsAction = QtWidgets.QAction(MainWindow)
        self.viewAllRatingsAction.setObjectName("viewAllRatingsAction")
        self.addRatingAction = QtWidgets.QAction(MainWindow)
        self.addRatingAction.setObjectName("addRatingAction")
        self.loginAction = QtWidgets.QAction(MainWindow)
        self.loginAction.setObjectName("loginAction")
        self.logoutAction = QtWidgets.QAction(MainWindow)
        self.logoutAction.setVisible(False)
        self.logoutAction.setObjectName("logoutAction")
        self.viewDocsAction = QtWidgets.QAction(MainWindow)
        self.viewDocsAction.setObjectName("viewDocsAction")
        self.viewAboutAction = QtWidgets.QAction(MainWindow)
        self.viewAboutAction.setObjectName("viewAboutAction")
        self.menuRating.addAction(self.viewMyRatingsAction)
        self.menuRating.addAction(self.viewAllRatingsAction)
        self.menuRating.addAction(self.addRatingAction)
        self.menuHelp.addAction(self.viewDocsAction)
        self.menuHelp.addAction(self.viewAboutAction)
        self.menuUser.addAction(self.loginAction)
        self.menuUser.addAction(self.logoutAction)
        self.menubar.addAction(self.menuRating.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menubar.addAction(self.menuUser.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Нажать"))
        self.label.setText(_translate("MainWindow", "TextLabel"))
        self.menuRating.setTitle(_translate("MainWindow", "Рейтинг"))
        self.menuHelp.setTitle(_translate("MainWindow", "Помощь"))
        self.menuUser.setTitle(_translate("MainWindow", "Пользователь"))
        self.viewMyRatingsAction.setText(_translate("MainWindow", "Мои рейтинги"))
        self.viewAllRatingsAction.setText(_translate("MainWindow", "Все рейтинги"))
        self.addRatingAction.setText(_translate("MainWindow", "Добавить рейтинг"))
        self.loginAction.setText(_translate("MainWindow", "Вход"))
        self.logoutAction.setText(_translate("MainWindow", "Выход"))
        self.viewDocsAction.setText(_translate("MainWindow", "Документация"))
        self.viewAboutAction.setText(_translate("MainWindow", "О программе"))
